### ISSUE TITLE
[BUG] Gallery does not display properly with flex

### ISSUE THREAD

**Issue by Cephalopode** [DivanteLtd/storefront-ui#1074]
**Describe the bug**
Gallery does not display properly when inside element where display: flex

**How to reproduce**
```
<div style="display:flex">
      <SfGallery :images="product.images" />
</div>
```
This bug is also appears in the storybook: 
[https://storybook.storefrontui.io/?path=/story/pages-product--common](https://storybook.storefrontui.io/?path=/story/pages-product--common)

**Devices**
- @storefront-ui : 0.7.1
 - Browser: Version 81.0.4044.113 (Official Build) (64-bit)
 - OS: Mac OS 10.11.6

![image](https://user-images.githubusercontent.com/24262995/79529591-0bf12400-803b-11ea-976d-999f7c275e9d.png)

**Comment by pspaczek** [comment]
@AdamPawlinski please check this issues :)

**Comment by Cephalopode** [comment]
Just found a quick and dirty fix. I noticed that if window gets resized, SfGallery component now displays correctly. So triggering a resize event just after mounting fixes the problem:
```
mounted() {
    this.$nextTick(() => {
      window.dispatchEvent(new Event('resize'))
    })
  },
```

**Comment by pspaczek** [comment]
fixed on 0.7.2

**Comment by pspaczek** [comment]
visible on the smallest screens

**Comment by scferrada** [comment]
Hi, I'm still experiencing the same problem. Is there a solution yet?

Thanks!

**Comment by AdamPawlinski** [comment]
@scferrada  I couldn't reproduce this error, so could please let me know when it appears and what version of SfUI are you using?

**Comment by scferrada** [comment]
@AdamPawlinski  here's my code:
`<div class="col-6">
          <SfGallery
            :images="images"/>
        </div>`

I have SfUI "0.7.18", the latest found with yarn.

Here's an image of the behaviour (the main image only appears after a resize event):
![imagen](https://user-images.githubusercontent.com/3776466/87190601-bdad9300-c2c0-11ea-9a2c-e5dce67520ec.png)
![imagen](https://user-images.githubusercontent.com/3776466/87190640-d0c06300-c2c0-11ea-8633-a220b0d26161.png)

**Comment by AdamPawlinski** [comment]
I'm sorry but still have no idea how to figure it out. Is that happen only on certain browser or system or on all versions?
